name: style

channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.8
  - pip>22.2
  - pytorch::pytorch=1.13.1
  - pytorch::torchvision
  - pytorch::torchaudio

  - pip:
      - pillow
      - matplotlib
      - torchmetrics
